const API_BASE_URL = "http://localhost:8080";

// AUTH CONTROLLER
const AUTH_PATH = API_BASE_URL + "/api/auth";

const LOGIN_URL = AUTH_PATH + "/login";
const REGISTER_URL = AUTH_PATH + "/register";
const LOGOUT_URL = AUTH_PATH + "/logout";
const REFRESH_TOKEN_URL = AUTH_PATH + "/refreshToken";

const GOOGLE_AUTH_URL =
  API_BASE_URL +
  "/oauth2/authorize/google?redirect_uri=http://localhost:8081/oauth2/redirect";

// TOPIC CONTROLLER
const TOPIC_PATH_URL = API_BASE_URL + "/api/topic";

const GET_ALL_TOPIC_URL = TOPIC_PATH_URL + "/all";
const DELETE_TOPIC_URL = TOPIC_PATH_URL + "/delete/";
const CREATE_TOPIC_URL = TOPIC_PATH_URL + "/create";
const UPDATE_TOPIC_URL = TOPIC_PATH_URL + "/update";
const UPDATE_TOPIC_CHAPTER_ORDER = TOPIC_PATH_URL + "/updateChapterOrder";

// CHAPTER CONTROLLER

const CHAPTER_PATH_URL = API_BASE_URL + "/api/chapter";

const GET_ALL_CHAPTERS_URL = CHAPTER_PATH_URL + "/getAllByTopicId";
const DELETE_CHAPTER_URL = CHAPTER_PATH_URL + "/delete/";
const CREATE_CHAPTER_URL = CHAPTER_PATH_URL + "/create";
const UPDATE_CHAPTER_URL = CHAPTER_PATH_URL + "/update";
const GET_CHAPTER_BY_ID_URL = CHAPTER_PATH_URL + "/";

// FILES CONTROLLER
const FILES_PATH_URL = API_BASE_URL + "/api/files";

const UPLOAD_FILE_URL = FILES_PATH_URL + "/upload";
const DELETE_FILE_URL = API_BASE_URL + "/";

// USER DETAIL CONTROLLER
const USER_DETAIL_PATH_URL = API_BASE_URL + "/api/user";

const GET_CURRENT_USER_DETAIL = USER_DETAIL_PATH_URL + "/currentUser";
const UPDATE_USER_DATA_URL = USER_DETAIL_PATH_URL + "/updateUserData"

// PROGRESS CONTROLLER
const PROGRESS_PATH_URL = API_BASE_URL + "/api/progress";

const UPDATE_CHAPTER_PROGRESS = PROGRESS_PATH_URL + "/chapter";
const GET_TOPIC_PROGRESS_BY_USER_ID = PROGRESS_PATH_URL + "/topics";

// COMMENT CONTROLLER
const COMMENT_PATH_URL = API_BASE_URL + "/api/comment/";

export const ApiPath = {
  LOGIN_URL,
  REGISTER_URL,
  LOGOUT_URL,
  GOOGLE_AUTH_URL,
  REFRESH_TOKEN_URL,
  GET_ALL_TOPIC_URL,
  DELETE_TOPIC_URL,
  CREATE_TOPIC_URL,
  UPDATE_TOPIC_URL,
  TOPIC_PATH_URL,
  UPDATE_TOPIC_CHAPTER_ORDER,
  GET_ALL_CHAPTERS_URL,
  CREATE_CHAPTER_URL,
  DELETE_CHAPTER_URL,
  UPDATE_CHAPTER_URL,
  GET_CHAPTER_BY_ID_URL,
  UPLOAD_FILE_URL,
  DELETE_FILE_URL,
  GET_CURRENT_USER_DETAIL,
  UPDATE_USER_DATA_URL,
  UPDATE_CHAPTER_PROGRESS,
  GET_TOPIC_PROGRESS_BY_USER_ID,
  COMMENT_PATH_URL
};
